- config.json
- exercises/practice/hello-world/.docs/instructions.md
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/hello-world/.meta/example.8th
- exercises/practice/hello-world/helloworld.8th
- exercises/practice/hello-world/helloworld_tests.8th
testing framework not present as yet
> lint fixes and hello world stubs

- exercises/practice/word-count/test-words.8th
word-count had a map comparison word in full. That's now been added to core.
> update to 22.08 which has m:= builtin

- exercises/practice/acronym/.meta/config.json
- exercises/practice/affine-cipher/.meta/config.json
- exercises/practice/gigasecond/.meta/config.json
- exercises/practice/luhn/.meta/config.json
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/trinary/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
- exercises/practice/word-count/.meta/config.json
- exercises/practice/yacht/.meta/config.json
This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.
> Reformat exercise config files

- docs/LEARNING.md
- docs/RESOURCES.md
- docs/SNIPPET.txt
- docs/TESTS.md
I think, once this is committed, that we can launch this language and I can get on with the next: OpenEuphoria.
> fixed learning, resources, snippet and tests

- bin/test
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/raindrops/.meta/example.8th
> Raindrops fix

- bin/test
- config.json
Just in case you see anything obvious @ErikSchierboom
> dos2unix and turning the track on

- config.json
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/darts/.meta/example.8th
- exercises/practice/darts/.meta/tests.toml
- exercises/practice/darts/darts-tests.8th
- exercises/practice/darts/darts.8th
- exercises/practice/darts/test-words.8th
- exercises/practice/darts/test.8th
Using the [Exercism's "Slimline September" to feature 8th](https://8th-dev.com/forum/index.php/topic,2713.0.html) thread on the 8th forum.
> Add Darts exercise

- exercises/practice/leap/leap-tests.8th
See
* https://github.com/exercism/problem-specifications/blob/b287cf50f11aad22f6c628035d096d422d5b9048/exercises/leap/canonical-data.json#L9
* https://github.com/exercism/problem-specifications/blob/b287cf50f11aad22f6c628035d096d422d5b9048/exercises/leap/canonical-data.json#L81
> Leap tests: years are transposed in two tests

- .github/workflows/test.yml
> Revert "Checkout using different token name"

- config.json
- exercises/practice/resistor-color/.docs/instructions.md
- exercises/practice/resistor-color/.meta/config.json
- exercises/practice/resistor-color/.meta/example.8th
- exercises/practice/resistor-color/.meta/tests.toml
- exercises/practice/resistor-color/resistor-color-tests.8th
- exercises/practice/resistor-color/resistor-color.8th
- exercises/practice/resistor-color/test-words.8th
- exercises/practice/resistor-color/test.8th
I ran config.json through jq which reformatted the whole thing. The only significant addition is
```json
{
"slug": "resistor-color",
"name": "Resistor Color",
"difficulty": 2,
"uuid": "cecddc24-225c-41a8-8331-d55d36e44c70",
"prerequisites": [],
"practices": []
},
```
> Add resistor-color exercise

- docs/INSTALLATION.md
Addresses [this forum thread](https://forum.exercism.org/t/8th-installation-doc-does-not-link-to-the-installer/7075)
> Add some details about how to acquire the installation zip file, and a warning for MacOS users

- exercises/practice/armstrong-numbers/.meta/tests.toml
- exercises/practice/armstrong-numbers/armstrong-numbers-tests.8th
- exercises/practice/gigasecond/.meta/tests.toml
- exercises/practice/luhn/.meta/tests.toml
- exercises/practice/trinary/.meta/tests.toml
- exercises/practice/word-count/.meta/tests.toml
- exercises/practice/yacht/.meta/tests.toml
`bin/configlet sync --tests include --update`
> Sync tests

- config.json
- exercises/practice/pythagorean-triplet/.docs/instructions.append.md
- exercises/practice/pythagorean-triplet/.docs/instructions.md
- exercises/practice/pythagorean-triplet/.meta/config.json
- exercises/practice/pythagorean-triplet/.meta/example.8th
- exercises/practice/pythagorean-triplet/.meta/tests.toml
- exercises/practice/pythagorean-triplet/pythagorean-triplet-tests.8th
- exercises/practice/pythagorean-triplet/pythagorean-triplet.8th
- exercises/practice/pythagorean-triplet/test-words.8th
- exercises/practice/pythagorean-triplet/test.8th
Add the `pythagorean-triplet` example. The instructions and such are taken from the C track exercise. The _.meta/example.8th_ implementation is my own, based on the article mentioned at the top of the file.
Please let me know how to improve this so it can be included. I've also started a thread on the 8th forum for feedback: https://8th-dev.com/forum/index.php/topic,2738.0.html
I don't have an actual Exercism development environment set up, so it may need some tweaks in the config files, etc., to pass muster. I hope someone can help me to verify that it works OK.
> Pythagorean triplet

- exercises/practice/acronym/libs/exercism/test
- exercises/practice/affine-cipher/libs/exercism/test
- exercises/practice/armstrong-numbers/libs/exercism/test
- exercises/practice/atbash-cipher/libs/exercism/test
- exercises/practice/bob/libs/exercism/test
- exercises/practice/collatz-conjecture/libs/exercism/test
- exercises/practice/darts/libs/exercism/test
- exercises/practice/gigasecond/libs/exercism/test
- exercises/practice/hamming/libs/exercism/test
- exercises/practice/hello-world/libs/exercism/test
- exercises/practice/isogram/libs/exercism/test
- exercises/practice/leap/libs/exercism/test
- exercises/practice/luhn/libs/exercism/test
- exercises/practice/pangram/libs/exercism/test
- exercises/practice/pythagorean-triplet/libs/exercism/test
- exercises/practice/raindrops/libs/exercism/test
- exercises/practice/resistor-color/libs/exercism/test
- exercises/practice/reverse-string/libs/exercism/test
- exercises/practice/roman-numerals/libs/exercism/test
- exercises/practice/series/libs/exercism/test
- exercises/practice/sieve/libs/exercism/test
- exercises/practice/triangle/libs/exercism/test
- exercises/practice/trinary/libs/exercism/test
- exercises/practice/two-fer/libs/exercism/test
- exercises/practice/word-count/libs/exercism/test
- exercises/practice/yacht/libs/exercism/test
- libs/README.md
- libs/exercism/test
- test-failure-demo.8th
This updates the test library for each exercise.
Also a demo script to show how presentation of actual and expected values looks like.
Output of demo script: https://gist.github.com/glennj/99759b6cd40a8f8416ddc81e93d5e7de
Fixes #105
> Failed tests to show actual and expected values.

- bin/add-exercise
- config.json
- exercises/practice/etl/.docs/instructions.md
- exercises/practice/etl/.docs/introduction.md
- exercises/practice/etl/.meta/config.json
- exercises/practice/etl/.meta/example.8th
- exercises/practice/etl/.meta/tests.toml
- exercises/practice/etl/etl.8th
- exercises/practice/etl/libs/exercism/test
- exercises/practice/etl/test.8th
Now that the test framework is in place, more exercises.
I set this one as "medium" difficulty.
> New exercise: ETL

- config.json
- exercises/practice/pop-count/.docs/instructions.md
- exercises/practice/pop-count/.docs/introduction.md
- exercises/practice/pop-count/.meta/config.json
- exercises/practice/pop-count/.meta/example.8th
- exercises/practice/pop-count/.meta/tests.toml
- exercises/practice/pop-count/libs/exercism/test
- exercises/practice/pop-count/pop-count.8th
- exercises/practice/pop-count/test.8th
New practice exercis: exercism/problem-specifications#2333
> New exercise: Pop Count

- README.md
To reduce the confusion as seen in, for example, #111
> add notes about contributing

- config.json
- exercises/practice/acronym/.meta/config.json
- exercises/practice/affine-cipher/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/bob/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/darts/.meta/config.json
- exercises/practice/eliuds-eggs/.meta/config.json
- exercises/practice/etl/.meta/config.json
- exercises/practice/gigasecond/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/luhn/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/pythagorean-triplet/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/resistor-color/.meta/config.json
- exercises/practice/reverse-string/.meta/config.json
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/series/.meta/config.json
- exercises/practice/sieve/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/trinary/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
- exercises/practice/word-count/.meta/config.json
- exercises/practice/yacht/.meta/config.json
@axtens @glennj The test library wasn't yet in the list of files used by the exercise, so changes to it wouldn't trigger an update message for the student. I think we should probably add this file as an invalidator.
> Add test file as invalidator

- exercises/practice/acronym/libs/exercism/test
- exercises/practice/affine-cipher/libs/exercism/test
- exercises/practice/armstrong-numbers/libs/exercism/test
- exercises/practice/atbash-cipher/libs/exercism/test
- exercises/practice/bob/libs/exercism/test
- exercises/practice/collatz-conjecture/libs/exercism/test
- exercises/practice/darts/libs/exercism/test
- exercises/practice/eliuds-eggs/libs/exercism/test
- exercises/practice/etl/libs/exercism/test
- exercises/practice/gigasecond/libs/exercism/test
- exercises/practice/hamming/libs/exercism/test
- exercises/practice/hello-world/libs/exercism/test
- exercises/practice/isogram/libs/exercism/test
- exercises/practice/leap/libs/exercism/test
- exercises/practice/luhn/libs/exercism/test
- exercises/practice/pangram/libs/exercism/test
- exercises/practice/pythagorean-triplet/libs/exercism/test
- exercises/practice/raindrops/libs/exercism/test
- exercises/practice/resistor-color/libs/exercism/test
- exercises/practice/reverse-string/libs/exercism/test
- exercises/practice/roman-numerals/libs/exercism/test
- exercises/practice/series/libs/exercism/test
- exercises/practice/sieve/libs/exercism/test
- exercises/practice/triangle/libs/exercism/test
- exercises/practice/trinary/libs/exercism/test
- exercises/practice/two-fer/libs/exercism/test
- exercises/practice/word-count/libs/exercism/test
- exercises/practice/yacht/libs/exercism/test
- libs/exercism/test
> Add check to validate the stack is the expected size

- config.json
- exercises/practice/pythagorean-triplet/.meta/config.json
I need to figure out why this fails CI.
> Apply configlet fmt

- bin/add-exercise
- bin/test
- bin/test-no-docker
Additional shellcheck suggestions.
Extends #146
> Add command-line options to add-exercise script.

- config.json
- exercises/practice/strain/.docs/instructions.md
- exercises/practice/strain/.meta/config.json
- exercises/practice/strain/.meta/example.8th
- exercises/practice/strain/.meta/tests.toml
- exercises/practice/strain/libs/exercism/test
- exercises/practice/strain/strain.8th
- exercises/practice/strain/test.8th
@axtens @glennj The nested lists test cases fail. I've checked the anonymous word being used there but it looks okay to me. What am I missing?
> Add `strain` exercise

- config.json
- exercises/practice/dnd-character/.docs/instructions.md
- exercises/practice/dnd-character/.docs/introduction.md
- exercises/practice/dnd-character/.meta/config.json
- exercises/practice/dnd-character/.meta/example.8th
- exercises/practice/dnd-character/.meta/tests.toml
- exercises/practice/dnd-character/dnd-character.8th
- exercises/practice/dnd-character/libs/exercism/test
- exercises/practice/dnd-character/test.8th
@glennj @axtens I was wondering how to best write the "check if a value is between a certain range" tests. Especially for the `character` generation, which generates a map (I haven't used an object here as we don't really update/do anything with the character).
> Add `dnd-character` exercise

- bin/test
> Skip food chain in CI

- bin/test
- exercises/practice/food-chain/.meta/example.8th
Thanks to @glennj's findings, I've been able to fix this.
> food-chain: fix

- exercises/practice/parallel-letter-frequency/.meta/example.8th
cause of the test failure in pr #189
> remove JSON literals from parallel-letter-frequency

- exercises/practice/pythagorean-triplet/.meta/example.8th
See https://github.com/exercism/8th/pull/203#issuecomment-2444117347
> replace pythagorean-triplet example solution, as current is causing "bad memory access or corruption"
